version: "3"
services:
  eldorado:
    container_name: eldorado
    build:
      context: eldorado
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: local
        TARGET_BRANCH: main
    depends_on:
      - dynamo_db
      - postgres_db
      - mongo_db
    environment:
      - WAIT_HOSTS=postgres_db:5432, dynamo_db:8000, mongo_db:27017
      - WAIT_TIMEOUT=60
      - WAIT_BEFORE=30
      - AWS_ACCESS_KEY_ID='FakeAccessKey'
      - AWS_SECRET_ACCESS_KEY='FakeSecretAccessKey'
      - REGION='us-east-1'
      - ENVIRONMENT='local'
    ports:
      - "8080:8080"
    links:
      - "dynamo_db"
      - "mongo_db"
      - "postgres_db"
    networks:
      customnetwork:
        ipv4_address: 172.20.0.10
    # command:
    #     dynamodb describe-limits --endpoint-url http://dynamodb-local:5952 --region us-east-1

  postgres_db:
    # https://hub.docker.com/_/postgres
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: dev_password
      POSTGRES_USER: dev_admin
    ports:
      - "5432:5432"
    networks:
      customnetwork:
        ipv4_address: 172.20.0.11

  dynamo_db:
    # https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    container_name: dynamo_db
    ports:
      - "8000:8000"
    networks:
      customnetwork:
        ipv4_address: 172.20.0.12
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal


  mongo_db:
    # https://hub.docker.com/_/mongo
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: eldorado
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      customnetwork:
        ipv4_address: 172.20.0.13


  challenges:
    container_name: challenges
    build:
      context: challenges
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: local
        TARGET_BRANCH: main
    environment:
      - ENVIRONMENT='local'
    ports:
      - "8001:8001"
    networks:
      customnetwork:
        ipv4_address: 172.20.0.14
      

networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16



