version: "3"
services:
  eldorado:
    build:
      context: devious
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: local
        TARGET_BRANCH: main
    environment:
      - WAIT_TIMEOUT=60
      - WAIT_BEFORE=30
    ports:
      - "8000:80"
